### ISSUE TITLE
Timestamp

### ISSUE THREAD

**Issue by IndigoColly** [FlyingDiver/Indigo-miniUniFi#14]
Hi Joe,
Request to add custom state to display time that client left the Network. Great work on this plugin.
Colly

**Comment by FlyingDiver** [comment]
You mean a formatted date/time, rather than the timestamp that's currently available? I'll be honest, I think this is something that ought to be done on the control page end of things (formatting data for display) rather than in the plugin.  I had hoped that users would be able to use something like the "Device Extensions" plugin to do this, but it doesn't do timestamps as an input type.  I need to see if there's some other alternative, or maybe write my own.

**Comment by IndigoColly** [comment]
Joe,

Yes I mean formatted date/time. I’m happy to do it on control page end, just throwing out options seeing as you’re in development stage.

Rgds

Colin

**Comment by FlyingDiver** [comment]
OK, I really don't want to be adding states unless it's absolutely necessary.  I added the "offline_seconds" one since I really wanted to display that information in the device status.

**Comment by jstewart99** [comment]
Not to belabor the issue but given that you have two early users now asking for this feature, I hope you'll consider it (rather than having to rely on an extra plug-in or making the user write their own scripts).  It's an easy conversion in Python:

from datetime import datetime
ts = int(last_seen)
last_seen_timestamp = datetime.utcfromtimestamp(ts).strftime('%Y-%m-%d %H:%M:%S')

"Offline_seconds" becomes pretty unwieldy on a Control Page for a device that's been offline for hours or days.  And knowing at a glance exactly when a device went offline seems helpful.  I know you're trying to avoid feature bloat, but I think it falls well under the "presence detection" umbrella.

@IndigoColly - you alluded to a workaround "on the Control Page end"...can you elaborate?  The only workaround I've come up with is using the basic script above to update a variable in a Schedule that runs every minute, but baking that into the plug-in would be a lot more elegant (and I'm sure will be appreciated by Joe's adoring fans when this is released). ;-)

**Comment by IndigoColly** [comment]
Hi Joseph,
I have a very inelegant way of dealing with this by updating a number of variables (insert timestamp into variable) via a trigger on device state change to store the last 4 times a device state becomes "up" or "down" (using the other Unifi plugin).  
Colly

**Comment by FlyingDiver** [comment]
The problem is not the actual conversion, I'm quite aware of how to do that.

The problem is feature creep.  I do it for this one state, then someone else asks for a conversion for a different state.  And it never stops.  The right answer is to make this kind of conversion/formatting easily available to control pages, not to modify every plugin to to do it.

**Comment by jstewart99** [comment]
> Hi Joseph,
> I have a very inelegant way of dealing with this by updating a number of variables (insert timestamp into variable) via a trigger on device state change to store the last 4 times a device state becomes "up" or "down" (using the other Unifi plugin).
> Colly

How DARE you use another UniFi plugin? Haha.  I thought 98% of the point of this plugin was to avoid that ugly mess.  The other plugin already shows this info in Timestamp format.  However, your comment gave me a fairly good idea for a workaround: Trigger: if device goes offline, run a python script to update a variable with the last_seen info converted into timestamp format.  Show that variable on the Control Page.  So it's showing "when device went offline" more than when it was last seen, but that's actually all I'm wanting to display anyway.  Thanks!

**Comment by IndigoColly** [comment]
Glad I could help you out (I'm normally the one getting help form everyone else :-) .. I use that way for a number of different devices.
